name = "BigWigSummary"
uuid = "7d082a81-8237-4692-9c6f-eb5a0bd5975b"
authors = ["Dongxu Yang"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
